### ISSUE TITLE
How do we stay out of the corner?

### ISSUE THREAD

**Issue by lethargilistic** [lethargilistic/ZombieGame#1]

**Comment by EveningFlame** [comment]
I think I am going to try the wall giving off a slight force field that is a little stronger than the zombie's push, but that means the rocks pull will need to be stronger than the force of the push.

**Comment by EveningFlame** [comment]
Here was Marriott's response to my question. In case we need some inspiration.

My advice is to add a second set of forces (as I mentioned in class) that repel from the walls.  It sounds like you already have tried this.  Let me address the method:

First you might have a test to only apply the force if you are close enough to the edge.  So you might have a code block like:

If (close to left wall) apply repulsion.

How should repulsion work?  Don't change the coordinate.  Instead  calculate a vector (the vector for the left wall is (1,0)) and multiply it by an acceleration.  Something between 0 and 1000000 would be good.  If it is not enough to overwhelm the zombie flight then increase this acceleration factor.  Add this vector to the action.direction.x and action.direction.y.  Don't overwrite the position or velocity vectors.  If the repulsion is not enough then multiply but a greater scalar value.
